
apiVersion: constraints.gatekeeper.sh/v1beta1
kind: NoUseOfDefaultServiceAccount
metadata:
  name: deny-default-service-account
spec:
  enforcementAction: deny
  match:
    kinds:
      - apiGroups: [""]
        kinds: ["Pod"]
