

---
apiVersion: networking.k8s.io/v1
kind: Ingress
metadata:
  name: ingress-hosts
  namespace: "{{ .Values.namespace }}"
  annotations:
    kubernetes.io/ingress.class: nginx
    cert-manager.io/cluster-issuer: letsencrypt-production
spec:
  ingressClassName: nginx
  rules:
    - host: "{{ .Values.ingressHost }}" 
      http:
        paths:
          - path: "/"
            pathType: Prefix
            backend:
              service:
                name: myapp-service-clusterip
                port:
                  number: {{ .Values.Port }}        
            