
---
apiVersion: v1
kind: Service
metadata:
  name: myapp-service-clusterip
  namespace: "{{ .Values.namespace }}"
spec:
  type: ClusterIP
  ports:
    - targetPort: {{ .Values.TargetPort }} 
      port: {{ .Values.Port }} 
  selector:
      project: myapp

