namespace: <your-namespace>
ContainerImageBase: <your-ecr-container-image-base>
RepositoryName: <your-repository-name>
ContainerTag: latest
Port: 3000
TargetPort: 3000
ingress:
ingressHost: <your-ingress-host>
image:
  pullPolicy: Always

